version: "3.9"

services:
  base:
    build:
      context: .
      dockerfile: base-env/Dockerfile
    image: base-env
    container_name: base-env
    ports:
      - "2222:22"

  spark:
    build:
      context: ./05-week
      dockerfile: Dockerfile
    image: spark-pyspark
    container_name: spark-week05
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./05-week/notebooks:/opt/notebooks
    depends_on:
      - base

jupyter:
    image: jupyter/pyspark-notebook:python-3.11
    container_name: jupyter-lab
    ports:
      - "8888:8888"
    volumes:
      - ./05-week/notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
    depends_on:
      - spark